### ISSUE TITLE
:main option

### ISSUE THREAD

**Issue by martinklepsch** [adzerk/boot-cljs#11]
Would it be possible to add a `:main` option to boot-cljs as it's described in [CLJS-851](http://dev.clojure.org/jira/browse/CLJS-851)?

It seems that the ticket is somewhat in limbo and maybe it can be implemented in a generic way that makes it easier further down the road to add features like splitting the compiled JS into multiple modules (see [shadow-build](https://github.com/thheller/shadow-build#simple-cljs-build)).

@micha is that something you think worth exploring for this project?

/cc @thheller A question about shadow-build: when using something like `:depends-on #{:mod-1 :mod-2}` in a module named `:mod-3` does that mean that the compilation output of `:mod-1` & `:mod-2` will be added to the compilation output of `:mod-3` or is the dependency information only required for proper compilation?

**Comment by micha** [comment]
Finalized in 5676b96023c6dafd7a8f9bef67883304de3c1c2e. It works!
