### ISSUE TITLE
Add "e externs" and "m preamble" cljs task options

### ISSUE THREAD

**Issue by numinasthmatic** [adzerk/boot-cljs#15]
base-opts contains empty vectors for :externs and :preamble.  base-opts is merged with various derived vectors into cljs-opts.  The preamble files are determined by searching for file extensions ".inc.js" in the input-files file set, and the external files by searching for ".ext.js" extensions in the same file set.

I suggest adding (initially) two arguments to the task options; "e externs" and "m preamble."  These would provide the initial contents of the vectors associated with the respective keys in base-opts, by searching for the named files in the input-files set, assuming that jar files in dependencies make their way into the input-files set.  If not, these jars must be searched separately from input-files for the named extern or preamble files.  Once this initial set for each of "externs and :preamble is determined, the existing by-ext searching can proceed and be merged with the initial option values.

I can try this out myself, but I'm not sure about the way dependencies are handled.  Are they included in input-files?

**Comment by micha** [comment]
Fixed in 5676b96023c6dafd7a8f9bef67883304de3c1c2e. Thanks!
