### ISSUE TITLE
Add docroot option

### ISSUE THREAD

**Issue by davesann** [adzerk/boot-cljs#17]
Currently is seems to be only possible to generate js files relative to the target directory directly.  

If you want to put the js under another path (output-to) and then serve from a subdirectory of target then the shim will break.

this is not an issue, other than for unified mode.

**Comment by Deraen** [comment]
Relative path changes in df5e91b24286a92fd316535f68a163a9abe05106 should fix this.

**Comment by micha** [comment]
Appears to be all :metal: and stuff. Feel free to reopen if symptoms persist for more than 4 hours.
