### ISSUE TITLE
Shim breaks when loaded from non root uri

### ISSUE THREAD

**Issue by Deraen** [adzerk/boot-cljs#18]
Shim works fine when used from `index.html`.
But when used from e.g. `posts/first.html` the relative urls don't work.

```
// boot-cljs shim
document.write("<script src='js/highlight.pack.inc.js'></script>");
document.write("<script src='out/goog/base.js'></script>");
document.write("<script src='boot-cljs-main.js'></script>");
document.write("<script>goog.require('main');</script>");
```

index.html: `<script src="main.js"></script>`
posts/first.html: `<script src="../main.js"></script>`

I wonder if main.js could somehow guess how it is being loaded.

**Comment by Deraen** [comment]
One possible hack would be to find the script tags on the page where src ends with shim file name and then use the start of src for script tags on the shim

Something like this should do:
```js
[].slice.call(document.getElementsByTagName("script")).filter(function(v) { return v.src.match(/main\.js$/); })[0].src;
```
(should probably use for loop etc. for IE8 compat)

- HTMLScriptElement.src is full URI, so we need to find difference to that from current URI
- First match should be the shim as shim and reload add their script tags after that
- Could still break if user has other scripts with same filename before shim...

**Comment by micha** [comment]
I think `scriptElement.getAttribute("src")` might do the trick, as it should be just the string value of the attribute, not the property.
