### ISSUE TITLE
Support arbitrary compiler options

### ISSUE THREAD

**Issue by martinklepsch** [adzerk/boot-cljs#27]
The CLJS compiler has more options than the `cljs` task in this project.
There should be a way to pass arbitrary options to the compiler
(I assume we don't want to add all of them as task options).

https://github.com/clojure/clojurescript/wiki/Compiler-Options

**Comment by micha** [comment]
We should take this opportunity to remove some of the less useful options we do have, maybe? Like `--output-dir`, `--pretty-print`, and `--no-warnings`, for example?
