### ISSUE TITLE
When having multiple outputs only one ends up in target directory

### ISSUE THREAD

**Issue by piranha** [adzerk/boot-cljs#32]
[Here is repository](https://github.com/piranha/switter) with a problem, when I compile things, it says:

```
Compiling boot-cljs-atom.js...
Compiling boot-cljs-ui.js...
```

But then

```
switter> ls target/boot-cljs*
target/boot-cljs-ui.js
```

This seems like a bug.

**Comment by micha** [comment]
This does indeed look like a bug, thanks for reporting it! I'll investigate.
