### ISSUE TITLE
:compiler-options in .cljs.edn behavior is a bit unexpected

### ISSUE THREAD

**Issue by piranha** [adzerk/boot-cljs#38]
The problem is if I put some compiler options in my cljs task (in `build.boot`), and have few `.cljs.edn` files, and one of them overrides some option, then other `.cljs.edn` files will have this option overriden to new value. I.e. if I have `{:target :nodejs}` for one file, I have to specify `{:target nil}` for another file explicitly. I don't think that was intended.

**Comment by stephanos** [comment]
Ah, maybe this explains #36

**Comment by piranha** [comment]
Hah, seems like the case. I guess you can try adding `{:target nil}`. :)

**Comment by micha** [comment]
I'm marking this as duplicate of #36.
