### ISSUE TITLE
Circular dependency when project defines main.cljs

### ISSUE THREAD

**Issue by jeluard** [adzerk/boot-cljs#42]
When a project defines a `main.cljs` file any attempt to compile will trigger a `Assert failed: Circular dependency detected [main]` error.

It looks like this is because `boot-cljs` generates a `main.cljs` file which requires project's `main` namespace.

**Comment by micha** [comment]
Do you have a main.cljs.edn file?

**Comment by jeluard** [comment]
No, do I need one?

**Comment by jeluard** [comment]
Closing as single segment namespace are now officially a bad practice.
