### ISSUE TITLE
Generated main.js includes Windows paths rather than URIs

### ISSUE THREAD

**Issue by lypanov** [adzerk/boot-cljs#43]
This is the next issue blocking boot-cljs on Windows (after 109 in the boot project). PRs coming soon.

**Comment by martinklepsch** [comment]
Just for reference: https://github.com/boot-clj/boot/pull/109

**Comment by lypanov** [comment]
Ah nice. Thanks Martin. Wasn't sure how to do that.

I've since pushed my changes to my repository: https://github.com/lypanov/boot-cljs/commit/fb9e0927166233c3ceaa1f2fae12076f11fc2e8c
And the needed helper which I felt probably best belonged in boot (but it's up to you guys): https://github.com/lypanov/boot/commit/63699b3b28aa999400c14e9f0077b7813e60ddd0

Looks like I need to read my git book on rebase before I can make a PR request alas else you'll end up with my ugly debug in the history.

**Comment by martinklepsch** [comment]
@lypanov this looks great.

I can't really help coordinating Windows improvements as I don't really have an overview what's going on. It's probably best if you join the #hoplon IRC channel and talk to @schmir, I think he has done a bunch of work on it in the last days. (In case you don't have an IRC client setup,  try [the webclient](http://webchat.freenode.net/?channels=hoplon))

**Comment by martinklepsch** [comment]
@lypanov is this still current?

**Comment by lypanov** [comment]
AFAIU yes. Alas I haven't managed to yet get boot into our production builds as no matter how many blockers I resolve we're still not getting advanced output to work. It's going to be a long road before I can invest time in something we're not actually able to use.

**Comment by lypanov** [comment]
2015-02-23 19:01:12.292:WARN:oejs.AbstractHttpConnection:/outgoog%08ase.js
java.io.IOException: The filename, directory name or volume label syntax is incorrect

Yes. This is still current.

**Comment by lypanov** [comment]
No longer using boot. I'll close the item.

**Comment by lypanov** [comment]
Anyway I see that https://github.com/adzerk/boot-cljs/commit/b8a5eaab854669d5c522276bf8fea2db3c1d2d7f would fix it. Missed this commit alas. Would have expected this issue to be updated.
