### ISSUE TITLE
Availabiltiy of latest release

### ISSUE THREAD

**Issue by danielsz** [adzerk/boot-cljs#51]
Latest release `[adzerk/boot-cljs "0.0-2814-0"]` can't be found on clojars.org.

**Comment by martinklepsch** [comment]
@micha I tried to push just now but got a "Forbidden" error. Can't look into it until later today. So if you can deploy it :+1:

**Comment by martinklepsch** [comment]
@alandipert just pushed it. :ship:

**Comment by danielsz** [comment]
:+1:
