### ISSUE TITLE
Failure to download ClojureScript dependency when relying on exclusions

### ISSUE THREAD

**Issue by jeluard** [adzerk/boot-cljs#56]
When I have an exclusion on `clojurescript` in my dependencies (e.g. `[secretary "1.2.0" :exclusions [org.clojure/clojurescript]]`) I get the following exception when running a `cljs` task:

```java
java.util.concurrent.ExecutionException: org.sonatype.aether.resolution.DependencyResolutionException: Could not find artifact org.clojure:clojurescript:jar:0.0.0 in clojars (http://clojars.org/repo/)
org.sonatype.aether.resolution.DependencyResolutionException: Could not find artifact org.clojure:clojurescript:jar:0.0.0 in clojars (http://clojars.org/repo/)
```

Not sure if this is an issue specific to this plugin or a more general restriction.

**Comment by martinklepsch** [comment]
Most likely caused by me not specifying a proper version here: https://github.com/adzerk/boot-cljs/blob/master/src/adzerk/boot_cljs.clj#L20

**Comment by jeluard** [comment]
Right it does not appear to be related to the `:exclusions` as I also get this when no `clojurescript` dependency can be transitively accessed.

It looks like `cljs` task gets the `clojurescript` dependency from the `cljs-repl` task. Using [saapas](https://github.com/Deraen/saapas) if you comment the `cljs-repl` task call you will see this exception.

That's a little confusing especially given that `boot-cljs` itself has a dependency on ClojureScript.

**Comment by martinklepsch** [comment]
> That's a little confusing especially given that boot-cljs itself has a dependency on ClojureScript.

Which is because it's scoped with `:scope "test"` — potentially this scoping should be removed?

**Comment by jeluard** [comment]
> Which is because it's scoped with :scope "test" — potentially this scoping should be removed?

Yes that confuses me too :) No change with or without.
